# Generated by Django 4.2.1 on 2023-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_dish_dishes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
