# Generated by Django 4.2.1 on 2023-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_cost_for_two',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bookform_webview_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_online_delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_table_booking',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='include_bogo_offer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_book_form_web_view',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_delevering_now',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='istable_reservation_supported',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opentable_support',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='switch_to_order_menu',
            field=models.IntegerField(null=True),
        ),
    ]
